FROM python:3.9-slim-buster

WORKDIR /app

# Using a less secure base image with unnecessary tools and potential vulnerabilities
USER root  

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . . 

CMD ["flask", "run", "--host=0.0.0.0"] #sample
