

# name: Build, Scan, Push, and Tag Docker Image to GCP Artifact Registry

# on:
#   push:
#     branches:
#       - main
# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: 'read'
#       id-token: 'write'

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - id: 'auth'
#         name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           token_format: 'access_token'
#           workload_identity_provider: 'projects/27439535227/locations/global/workloadIdentityPools/githubactions/providers/github'
#           service_account: 'github-serviceaccount@rapid-strength-422813-t9.iam.gserviceaccount.com'

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1

#       - name: Configure Docker for Artifact Registry
#         run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

#       - name: Extract Version from Tag
#         id: extract_version
#         run: |
#           VERSION=$(echo $GITHUB_REF | awk -F / '{print $3}')
#           echo "VERSION=${VERSION}" >> $GITHUB_ENV

#       - name: Build and Tag Docker Image
#         run: |
#           docker build -t asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:$GITHUB_SHA .
#           docker tag asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:$GITHUB_SHA asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:${{ env.VERSION }}

#       - name: Scan Docker Image for Vulnerabilities (Trivy)
#         uses: aquasecurity/trivy-action@master
#         with:
#           image-ref: 'asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:${{ env.VERSION }}'
#           format: 'table'
#           exit-code: '1'
#           severity: 'CRITICAL,HIGH' 

#       - name: Push Docker Images
#         run: |
#           docker push asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:$GITHUB_SHA
#           docker push asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:${{ env.VERSION }}



name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ui-web-app
      PROJECT_ID: rapid-strength-422813-t9
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 

    # - uses: google-github-actions/setup-gcloud@v1
    #   with:
    #     service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    #     project_id: ${{ env.PROJECT_ID }}
    #     export_default_credentials: true

    # - name: Authenticate Docker with gcloud
    #   uses: google/cloud-actions/gcloud-auth@v2
    #   with:
    #     service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    #     scopes: ['https://www.googleapis.com/auth/cloud-platform']
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Build and Tag Docker Image
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:latest
        docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:$GIT_TAG
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker push asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:latest
        docker push asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:$GIT_TAG