name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ui-web-app
      PROJECT_ID: rapid-strength-422813-t9
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v minor

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Build and Tag Docker Image
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:latest
        docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:$GIT_TAG

    # Docker Scanner with Vulnerability Check
    - name: Scan for vulnerabilities (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image: $IMAGE_NAME:latest
        format: table  # Adjust format (e.g., json, sarif)
        exit-code: 1   # Fail workflow if vulnerabilities are found
        vuln-type: os,library  # Adjust vulnerability types to scan
        severity: CRITICAL,HIGH  # Adjust severity levels to consider critical

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker push asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:latest
        docker push asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app:$GIT_TAG