name: Build, Scan, Push, and Tag Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor # Increment the minor version (e.g., 1.0.0 -> 1.1.0)

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
        token_format : 'access_token'
          workload_identity_provider: projects/27439535227/locations/global/workloadIdentityPools/k8s-pools/providers/k8s-provider
          service_account: github-serviceaccount@rapid-strength-422813-t9.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=$(echo $GITHUB_REF | awk -F / '{print $3}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:$GITHUB_SHA .
          docker tag asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:$GITHUB_SHA asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:${{ env.VERSION }}

      - name: Scan Docker Image for Vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:${{ env.VERSION }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH' 

      - name: Push Docker Images
        run: |
          docker push asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:$GITHUB_SHA
          docker push asia-southeast1-docker.pkg.dev\rapid-strength-422813-t9\dbs-ui-web-app\ui-app:1.0.3:${{ env.VERSION }}
